### ISSUE TITLE
✓ KivyMD. TODO List

### ISSUE THREAD

**Issue by ArtemSBulgakov** [kivymd/KivyMD#139]
TODO List
=========

This is the list that contains all ideas about KivyMD. Please create issues with feature description if you really need it.

KivyMD library - components
---------------------------

[`kivymd/KivyMD`](https://github.com/kivymd/KivyMD) repository

- [x] Labels
  - [x] MDLabel
  - [x] MDIcon
    - [x] Support for using standard sizes (like 32x, 48x)
    - [x] Support for images inside MDIcon widget
    - [ ] Animation for icon changes
- [x] Buttons
  - [Material Design spec, Buttons](https://m3.material.io/components/all-buttons)
  - [Material Design spec, Buttons: floating action button](https://m3.material.io/components/floating-action-button/overview)
  - [x] Can we join all MD* buttons to one MDButton class?
    - May be use `type` property for different styles
- [x] Text fields
  - [Material Design spec, Text fields](https://m3.material.io/components/text-fields/overview)
  - [x] Type: line
  - [x] Type: filled
    - [x] Round
      - Can we join MDTextFieldRound with MDTextField to use `type` property for changing style?
  - [x] Type: outlined
- [x] Selection controls
  - [x] [Checkbox](https://m3.material.io/components/checkbox/overview)
    - [x] Make animation of checking/unchecking  more like in specification
  - [x] [Radio button](https://m3.material.io/components/radio-button/overview)
  - [x] [Switch](https://m3.material.io/components/switch/overview)
- [x] Cards
  - [Material Design spec, Cards](https://m3.material.io/components/cards/overview)
  - [x] Elevation on hover
  - [x] Button behavior with ripple
- [ ] Search
  - [Material Design spec, Search](https://m3.material.io/components/search/overview)
- [x] Chips
  - [Material Design spec, Chips](https://m3.material.io/components/chips/overview)
- [x] Dialogs
  - [Material Design spec, Dialogs](https://m3.material.io/components/dialogs/overview)
- [x] Dividers
  - [Material Design spec, Dividers](https://m3.material.io/components/divider/overview)
- [x] Data tables
  - [Material Design spec, Data tables](https://material.io/components/data-tables/)
  - https://gitlab.com/zuhaib/KivyMD/tree/feature/DataTable
- [x] Image lists
  - [Material Design spec, Image lists](https://material.io/components/image-lists/)
- [x] Lists
  - [Material Design spec, Lists](https://m3.material.io/components/lists/overview)
- [x] Menus
  - [Material Design spec, Menus](https://m3.material.io/components/menus/overview)
- [x] Navigation drawer
  - [Material Design spec, Navigation drawer](https://m3.material.io/components/navigation-drawer/overview)
- [x] Pickers
  - [Time picker](https://m3.material.io/components/time-pickers/overview)
  - [Date picker](https://m3.material.io/components/date-pickers/overview)
- [x] Progress indicators
  - [Material Design spec, Progress indicators](https://m3.material.io/components/progress-indicators/overview)
- [x] App bars
  - [Material Design spec, App bars: top](https://m3.material.io/components/top-app-bar/overview)
  - [Material Design spec, App bars: bottom](https://m3.material.io/components/bottom-app-bar/overview)
- [x] Navigation bar
  - [Material Design spec, Navigation bar](https://m3.material.io/components/navigation-bar/overview)
- [x] Sheets
  - [Material Design spec, Sheets: bottom](https://m3.material.io/components/bottom-sheets/overview)
  - [Material Design spec, Sheets: side](https://m3.material.io/components/side-sheets/overview)
- [x] Sliders
  - [Material Design spec, Sliders](https://m3.material.io/components/sliders/overview)
- [x] Snackbars
  - [Material Design spec, Snackbars](https://m3.material.io/components/snackbar/overview)
- [x] Tabs
  - [Material Design spec, Tabs](https://m3.material.io/components/tabs/overview)
- [x] Tooltips
  - [Material Design spec, Tooltips](https://m3.material.io/components/tooltips/overview)
  - [x] Direction of the tooltip (left/top/right/bottom)
  - [x] Time delay before showing tooltip
  - [x] Feature to show tooltip by function call, not by hover

KivyMD library - modules
------------------------

- [x] App
  - MDApp class that has theme manager object
- [x] Toast
- [x] Theming
  - [x] Theme class
    - Fast theme changing
- [ ] Navigation
  - [Material Design spec, Understanding navigation](https://material.io/design/navigation/understanding-navigation.html)
  - [Material Design spec, Navigation transitions](https://material.io/design/navigation/navigation-transitions.html)
  - [ ] Function in MDApp that can automatically set animation of transition between screens (that depend on position of previous and next screen in the [screen tree](https://material.io/design/navigation/understanding-navigation.html#types-of-navigation])

Automation
----------

- [x] Auto formatting with Black
  - [x] Checking formatting via GitHub Actions
- [x] Script for making release
- [x] Auto deploying to PyPI
- [ ] Signing packages published to PyPI
- [ ] Signing demos binaries
- [ ] Publish demos to Play Store (autopublishing)
- [ ] Tests for main modules
- [ ] Tests for demos
- [ ] Generation videos (gifs) and screenshots for documentation

Demos
-----

- [x] Make studies as individual demos
- [ ] Test mode for Kitchen Sink demo (runs all demo widgets)
- [x] Add Readme for each app

Documentation
-------------

- [x] Make one-style documentation for all modules
- [x] Generating documentation for GitHub pages
- [ ] Documentation standards for KivyMD Extensions
- [ ] Documentation for developers

KivyMD Website
--------------

`kivymd/website` repository

- [ ] Collect all documentation (KivyMD, KivyMD Extensions) into one website
- [ ] Buy domain
- [ ] Publish development documentaion in `dev` subdomain
- [ ] Publish public keys in `keys` subdomain
- [ ] Make documentation using Material-UI ([example](https://material-ui.com/components))
- [ ] Connect translation system
- [ ] Make documentation as pdf
- [ ] Page with statistics
  - Website pages views
  - KivyMD library installs, downloads, clones
  - Extensions statistics
  - Discord server statistics
  - Other statistics
- [ ] Badges: `kivymd-official`, `kivymd-internal`, `kivymd-extensions`, `kivymd-unofficial`
  - Page where listed all projects with these badges
- [ ] Page with all links related to KivyMD

KivyMD Extensions
-----------------

[`kivymd-extensions`](https://github.com/kivymd-extensions) organization,
[`kivymd-extensions/KivyMD_Extensions`](https://github.com/kivymd-extensions/KivyMD_Extensions) repository,
[`kivymd-extensions/extension_template`](https://github.com/kivymd-extensions/extension_template) repository

- [ ] Workflow to check package structure
  - Don't allow to edit `kivymd_extensions/__init__.py` file
  - Check that there is `__version__` in `__init__.py`
- [ ] Documentation for developers

KivyMD Template
---------------

`kivymd/KivyMD_Template` repository

- [ ] Create KivyMD_Template utility - generator for new apps/packages/extensions
- [ ] Create KivyMD_Template_Sample repository - template repository that user can just clone
- [ ] Command line interface (CLI)
- [ ] Graphical interface (GUI)
- [ ] Show list of commands that utility will run
- [ ] Show resulting file structure (before real creation)

Features:

- [ ] Setup settings
  - PyCharm settings (`.idea` directory)
  - Git (`.gitignore`, `.gitattributes`, pre-commit), branches
  - Tools: autoformatters, linters
  - Packaging tools (Buildozer, PyInstaller)
  - CI (GitHub Actions)
- [ ] Create screens
- [ ] Create asynchronous classes: connection with API (asynchronous loading), 
- [ ] Customize theme

KivyMD Bot
----------

`kivymd/kivymd_bot` repository

GitHub:

- [ ] Welcoming new contributors
- [ ] Pushing binaries, build website to kivymd/storage repository
- [ ] Pull request status in second comment
- [ ] Autolabeling, autoclosing, autolocking, autoassigning
- [ ] Storing keys, signing packages, posting packages to PyPI
- [ ] Marking donaters/sponsors
- [ ] Autohide private, illegal or spam messages
- [ ] Contacting sponsors to notify about their privileges
- [ ] Synchronizing labels among all KivyMD repositories

Discord:

- [ ] Welcoming new members (in direct message)
- [ ] Controlling rules
  - Duplicate messages
- [ ] Commands
  - Quick search in documentation
  - Instructions
- [ ] Posting GitHub updates
  - Edit message when comment has been edited on GitHub
  - Edit message with pull request status
- [ ] Autosetting roles (sponsors/extensions developers)
- [ ] Posting announcements about new releases

Development workflow
--------------------

- [ ] Development in `dev` branch, latest release in `main` branch
- [x] Structured labels
  - Scope: uix, tests, theming
  - Type: bug, enhancement; for KivyMD Extensions: new extension, extension request
  - Platform: android, ios, windows, linux, mac
  - Resolution: fixed, won't fix, rejected (for feature requests), out of date (already fixed in dev), duplicate, invalid
  - Priority: critical, high, normal, low
  - Bounty: has bounty; amount
  - Sponsoring level: donator, backer, gold sponsor
- [ ] Milestones
  - New releases
  - Large features
- [ ] Projects

Sponsoring
----------

[`kivymd`](https://opencollective.com/kivymd) collective on OpenCollective

- [ ] Accepting cryptocurrency donations
- [ ] Automate bounty setting (if somebody sent a donation with message - issue id)

Design
------

- [x] New color from Material palette that will be used for all our design
- [ ] New logo that fits Material style and can be exported as .svg
  - KivyMD
  - KivyMD Extensions
  - KivyMD Template
  - KivyMD Collection
  - KivyMD Bot
  - Social preview

Other
-----

- [ ] Rebase KivyMD repository
  - Include old commits (currently all commits from older repositories are squashed into one)
  - Remove large files (replace them with empty file), decrease repository size
  - Fix commits author if there were any mistakes

**Comment by rhandel** [comment]
I vote for a kivymd.uix.filemanager (aka MDFileManager) change.

Add chroot style functionality so that the user is presented ONLY with the chroot'ed directory (in the header) of the directory displayed.  Fixing the root directory and making MDFileManager display the root directory only.

Example:
directory /home/uname/files/...
chroot'ed to /home/uname/files/subdirectories
would display files/subdirectories (nothing above that files)

This would make Android/iOS development a LOT easier.
